from __future__ import annotations

import argparse
import json
from pathlib import Path
from statistics import mean

from medical_rag.chunking import StructureAwareChunker
from medical_rag.parsing.models import CleanedDocument


def _write_json(path: Path, payload: object) -> None:
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def _render_preview(chunks: list[object]) -> str:
    sections: list[str] = []
    for chunk in chunks:
        section = chunk.section or "（未识别章节）"
        page_label = (
            f"PAGE {chunk.page_start}"
            if chunk.page_start == chunk.page_end
            else f"PAGES {chunk.page_start}-{chunk.page_end}"
        )
        title = (
            f"TABLE · {chunk.table_title or chunk.chunk_id}"
            if chunk.content_type == "table"
            else f"NARRATIVE · {section}"
        )
        sections.append(
            "\n".join(
                [
                    f"## {title}",
                    "",
                    f"- chunk_id: `{chunk.chunk_id}`",
                    f"- {page_label}",
                    f"- chars: {chunk.char_count}",
                    f"- section_path: {' > '.join(chunk.section_path) or '—'}",
                    "",
                    chunk.text,
                ]
            )
        )
    return "\n\n---\n\n".join(sections)


def run(
    input_json: Path,
    output_dir: Path,
    *,
    target_chars: int,
    max_chars: int,
    min_chars: int,
    overlap_chars: int,
) -> None:
    payload = json.loads(input_json.read_text(encoding="utf-8"))
    document = CleanedDocument.model_validate(payload)

    chunker = StructureAwareChunker(
        target_chars=target_chars,
        max_chars=max_chars,
        min_chars=min_chars,
        overlap_chars=overlap_chars,
    )
    chunked = chunker.chunk(document)

    output_dir.mkdir(parents=True, exist_ok=True)
    chunks_path = output_dir / "chunks.json"
    preview_path = output_dir / "chunks_preview.md"
    report_path = output_dir / "chunk_report.json"

    _write_json(chunks_path, [chunk.model_dump(mode="json") for chunk in chunked.chunks])
    preview_path.write_text(_render_preview(chunked.chunks), encoding="utf-8")

    narrative = [chunk for chunk in chunked.chunks if chunk.content_type == "narrative"]
    tables = [chunk for chunk in chunked.chunks if chunk.content_type == "table"]
    lengths = [chunk.char_count for chunk in chunked.chunks]
    sections = sorted({chunk.section for chunk in chunked.chunks if chunk.section})

    report = {
        "document_id": chunked.document_id,
        "source_file": chunked.source_file,
        "chunk_count": len(chunked.chunks),
        "narrative_chunk_count": len(narrative),
        "table_chunk_count": len(tables),
        "section_count": len(sections),
        "min_chunk_chars": min(lengths) if lengths else 0,
        "avg_chunk_chars": round(mean(lengths), 2) if lengths else 0,
        "max_chunk_chars": max(lengths) if lengths else 0,
        "cross_page_chunk_count": sum(
            1 for chunk in narrative if chunk.page_start != chunk.page_end
        ),
        "config": {
            "target_chars": target_chars,
            "max_chars": max_chars,
            "min_chars": min_chars,
            "overlap_chars": overlap_chars,
        },
    }
    _write_json(report_path, report)

    print(json.dumps(report, ensure_ascii=False, indent=2))
    print(f"\nArtifacts written to: {output_dir.resolve()}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Structure-aware chunking for a cleaned document")
    parser.add_argument(
        "cleaned_document",
        type=Path,
        help="Path to cleaned_document.json generated by scripts/parse_pdf.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory; defaults to the cleaned document's directory",
    )
    parser.add_argument("--target-chars", type=int, default=800)
    parser.add_argument("--max-chars", type=int, default=1200)
    parser.add_argument("--min-chars", type=int, default=180)
    parser.add_argument("--overlap-chars", type=int, default=120)
    args = parser.parse_args()

    output_dir = args.output_dir or args.cleaned_document.parent
    run(
        args.cleaned_document,
        output_dir,
        target_chars=args.target_chars,
        max_chars=args.max_chars,
        min_chars=args.min_chars,
        overlap_chars=args.overlap_chars,
    )


if __name__ == "__main__":
    main()
